source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ModuleKit_Example', :exclusive => true do
  pod 'ModuleKit', :path => '../'
end

target 'ModuleKit_Tests', :exclusive => true do
  pod 'ModuleKit', :path => '../'

  pod 'FBSnapshotTestCase'
end
